version: "3.9"

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - php-fpm
    networks:
      - net-nginx-php
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/app:/var/www/html/storage/app:ro

  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
    volumes:
        - mysqldata:/var/lib/mysql/
    networks:
        - net-php-mysql
  php-fpm:
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        WWW_USER: ${WWW_USER}
        WWW_GROUP: ${WWW_GROUP}
    user: ${WWW_USER}:${WWW_GROUP}
    depends_on:
      - mysql # condition: service_healthy
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini

    networks:
      - net-php-mysql
      - net-nginx-php

networks:
  net-nginx-php:
    driver: bridge
  net-php-mysql:
    driver: bridge

volumes:
    mysqldata:
